name: build-dlls

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-windows-x64:
    name: Build Windows (x64)
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test cmake installation
        run: cmake --version
      - name: Build Luau
        run: |
          cmake -S . -B build -A x64 -DLUAU_BUILD_CLI=OFF -DLUAU_BUILD_TESTS=OFF -DLUAU_EXTERN_C=ON -DLUAU_BUILD_SHARED=ON
          cmake --build build --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Luau Windows (x64)
          path: build/Release
  build-windows-arm:
    name: Build Windows (ARM)
    runs-on: windows-11-arm
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test cmake installation
        run: cmake --version
      - name: Build Luau
        run: |
          cmake -S . -B build -A ARM64 -DLUAU_BUILD_CLI=OFF -DLUAU_BUILD_TESTS=OFF -DLUAU_EXTERN_C=ON -DLUAU_BUILD_SHARED=ON
          cmake --build build --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Luau Windows (ARM)
          path: build/Release
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test cmake installation
        run: cmake --version
      - name: Build Luau
        run: |
          cmake -S . -B build-macos-universal -G Ninja -DCMAKE_BUILD_TYPE=Release -DLUAU_BUILD_CLI=OFF -DLUAU_BUILD_TESTS=OFF -DLUAU_EXTERN_C=ON -DLUAU_BUILD_SHARED=ON -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
          cmake --build build-macos-universal
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Luau macOS
          path: |
            build/*.dylib
            build/*.a
  build-linux-x64:
    name: Build Linux (x64)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test cmake installation
        run: cmake --version
      - name: Build Luau
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DLUAU_BUILD_CLI=OFF -DLUAU_BUILD_TESTS=OFF -DLUAU_EXTERN_C=ON -DLUAU_BUILD_SHARED=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Luau Linux (x64)
          path: |
            build/*.so
            build/*.a
  build-linux-arm:
    name: Build Linux (ARM)
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test cmake installation
        run: cmake --version
      - name: Build Luau
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DLUAU_BUILD_CLI=OFF -DLUAU_BUILD_TESTS=OFF -DLUAU_EXTERN_C=ON -DLUAU_BUILD_SHARED=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Luau Linux (ARM)
          path: |
            build/*.so
            build/*.a